import json
import logging
import os
import httpx
from fastapi import APIRouter, HTTPException
from langchain_openai import ChatOpenAI

from api.models.schemas import RoadmapRefreshRequest, RoadmapItemUpdateRequest
from api.lib.supabase import (
    _supabase_headers,
    _encode_eq,
    _safe_user_id,
    _list_chat_sessions,
    _get_recent_chat_history,
    _get_allowed_sources,
    SUPABASE_URL
)

router = APIRouter(prefix="/api/roadmap")
logger = logging.getLogger(__name__)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
DEFAULT_MODEL = os.getenv("DEFAULT_MODEL", "gpt-4o-mini")

def _generate_roadmap_with_llm_from_behavior(user_id: str) -> list[dict]:
    if not OPENAI_API_KEY:
        raise HTTPException(status_code=500, detail="OPENAI_API_KEY is required for roadmap generation")

    sessions = _list_chat_sessions(user_id, limit=10)
    all_sources = _get_allowed_sources(user_id)

    history = []
    for s in sessions[:5]:
        sid = str(s.get("session_id") or "")
        if sid:
            history.extend(_get_recent_chat_history(user_id, sid, limit=12))

    user_messages = [str(h.get("content") or "").strip() for h in history if str(h.get("role") or "") == "user"]
    assistant_messages = [str(h.get("content") or "").strip() for h in history if str(h.get("role") or "") == "assistant"]

    behavior_payload = {
        "user_id": user_id,
        "recent_sessions": [s.get("session_id") for s in sessions[:5]],
        "recent_user_messages": user_messages[-30:],
        "recent_assistant_messages": assistant_messages[-20:],
        "available_sources": all_sources[:30],
        "requirements": {
            "item_count": 4,
            "id_format": "rm-1, rm-2, ...",
            "priority_values": ["high", "medium", "low"],
            "status_default": "todo",
            "progress_range": [0, 100],
            "include_fields": ["id", "topic", "description", "priority", "eta_minutes", "progress", "status", "sources", "actions"],
            "language": "vi",
        },
    }

    llm = ChatOpenAI(model=DEFAULT_MODEL, api_key=OPENAI_API_KEY, temperature=0.2)
    resp = llm.invoke([
        {"role": "system", "content": "You are an academic learning planner. Build a personalized roadmap strictly from user behavior evidence. Return STRICT JSON array only, no markdown."},
        {"role": "user", "content": json.dumps(behavior_payload, ensure_ascii=False)},
    ])

    raw = (resp.content or "").strip()
    parsed = json.loads(raw)
    if not isinstance(parsed, list) or not parsed:
        raise HTTPException(status_code=500, detail="Invalid roadmap JSON generated by LLM")

    normalized = []
    for idx, item in enumerate(parsed, start=1):
        if not isinstance(item, dict):
            continue
        normalized.append({
            "id": str(item.get("id") or f"rm-{idx}"),
            "topic": str(item.get("topic") or f"Roadmap item {idx}"),
            "description": str(item.get("description") or ""),
            "priority": str(item.get("priority") or "medium").lower() if str(item.get("priority") or "medium").lower() in {"high", "medium", "low"} else "medium",
            "eta_minutes": max(10, min(int(item.get("eta_minutes", 30)), 240)),
            "progress": max(0, min(int(item.get("progress", 0)), 100)),
            "status": str(item.get("status") or "todo").lower() if str(item.get("status") or "todo").lower() in {"todo", "doing", "done"} else "todo",
            "sources": [str(s) for s in (item.get("sources") or []) if str(s).strip()],
            "actions": [str(a) for a in (item.get("actions") or []) if str(a).strip()][:6],
        })

    if not normalized:
        raise HTTPException(status_code=500, detail="No valid roadmap items generated")
    return normalized

def _save_roadmap_plan(user_id: str, mode: str, items: list[dict]) -> dict:
    headers = _supabase_headers()
    headers["Prefer"] = "return=representation"

    next_action = next((i for i in items if i.get("status") != "done"), items[0] if items else None)
    summary = f"Roadmap generated with {len(items)} items"
    plan_payload = {
        "user_id": user_id,
        "mode": mode,
        "summary": summary,
        "next_action_item_id": (next_action or {}).get("id"),
    }

    with httpx.Client(timeout=15.0) as client:
        plan_resp = client.post(f"{SUPABASE_URL}/rest/v1/roadmap_plans", headers=headers, json=plan_payload)
    if plan_resp.status_code >= 300:
        raise HTTPException(status_code=500, detail=f"Failed to save roadmap plan: {plan_resp.text}")

    plan_rows = plan_resp.json()
    if not plan_rows:
        raise HTTPException(status_code=500, detail="Roadmap plan save returned empty response")
    plan = plan_rows[0]
    plan_id = str(plan.get("id"))

    item_headers = _supabase_headers()
    item_headers["Prefer"] = "resolution=merge-duplicates,return=representation"
    item_payloads = []
    for item in items:
        item_payloads.append({
            "plan_id": plan_id,
            "item_key": item.get("id"),
            "topic": item.get("topic"),
            "description": item.get("description"),
            "priority": item.get("priority"),
            "eta_minutes": int(item.get("eta_minutes", 30)),
            "progress": int(item.get("progress", 0)),
            "status": item.get("status", "todo"),
            "sources": item.get("sources", []),
            "actions": item.get("actions", []),
        })

    with httpx.Client(timeout=15.0) as client:
        items_resp = client.post(f"{SUPABASE_URL}/rest/v1/roadmap_items", headers=item_headers, json=item_payloads)
    if items_resp.status_code >= 300:
        raise HTTPException(status_code=500, detail=f"Failed to save roadmap items: {items_resp.text}")

    saved_items_rows = items_resp.json()
    saved_items = []
    for r in saved_items_rows:
        saved_items.append({
            "id": r.get("item_key"),
            "topic": r.get("topic"),
            "description": r.get("description"),
            "priority": r.get("priority"),
            "eta_minutes": r.get("eta_minutes"),
            "progress": r.get("progress"),
            "status": r.get("status"),
            "sources": r.get("sources") or [],
            "actions": r.get("actions") or [],
        })

    next_action_saved = next((i for i in saved_items if i.get("status") != "done"), saved_items[0] if saved_items else None)
    return {"plan": plan, "items": saved_items, "next_action": next_action_saved}

def _load_latest_roadmap_plan(user_id: str) -> dict | None:
    headers = _supabase_headers()
    plan_url = (
        f"{SUPABASE_URL}/rest/v1/roadmap_plans"
        f"?user_id=eq.{_encode_eq(user_id)}"
        f"&select=id,user_id,mode,summary,next_action_item_id,generated_at,updated_at"
        f"&order=generated_at.desc"
        f"&limit=1"
    )

    with httpx.Client(timeout=15.0) as client:
        plan_resp = client.get(plan_url, headers=headers)
    if plan_resp.status_code >= 300:
        raise HTTPException(status_code=500, detail=f"Failed to load roadmap plan: {plan_resp.text}")
    plan_rows = plan_resp.json()
    if not plan_rows:
        return None

    plan = plan_rows[0]
    plan_id = str(plan.get("id"))
    items_url = (
        f"{SUPABASE_URL}/rest/v1/roadmap_items"
        f"?plan_id=eq.{_encode_eq(plan_id)}"
        f"&select=item_key,topic,description,priority,eta_minutes,progress,status,sources,actions,updated_at"
        f"&order=updated_at.asc"
    )
    with httpx.Client(timeout=15.0) as client:
        items_resp = client.get(items_url, headers=headers)
    if items_resp.status_code >= 300:
        raise HTTPException(status_code=500, detail=f"Failed to load roadmap items: {items_resp.text}")

    item_rows = items_resp.json()
    items = [
        {
            "id": r.get("item_key"),
            "topic": r.get("topic"),
            "description": r.get("description"),
            "priority": r.get("priority"),
            "eta_minutes": r.get("eta_minutes"),
            "progress": r.get("progress"),
            "status": r.get("status"),
            "sources": r.get("sources") or [],
            "actions": r.get("actions") or [],
        }
        for r in item_rows
    ]
    next_action = next((i for i in items if i.get("status") != "done"), items[0] if items else None)
    return {"plan": plan, "items": items, "next_action": next_action}

def _update_roadmap_item_db(user_id: str, item_id: str, status: str, progress: int | None = None) -> dict:
    latest = _load_latest_roadmap_plan(user_id)
    if not latest:
        raise HTTPException(status_code=404, detail="No roadmap plan found for user")

    plan_id = str((latest.get("plan") or {}).get("id") or "")
    if not plan_id:
        raise HTTPException(status_code=404, detail="Invalid roadmap plan")

    payload = {"status": status}
    if progress is not None:
        payload["progress"] = max(0, min(int(progress), 100))

    headers = _supabase_headers()
    headers["Prefer"] = "return=representation"
    patch_url = (
        f"{SUPABASE_URL}/rest/v1/roadmap_items"
        f"?plan_id=eq.{_encode_eq(plan_id)}"
        f"&item_key=eq.{_encode_eq(item_id)}"
    )
    with httpx.Client(timeout=15.0) as client:
        patch_resp = client.patch(patch_url, headers=headers, json=payload)
    if patch_resp.status_code >= 300:
        raise HTTPException(status_code=500, detail=f"Failed to update roadmap item: {patch_resp.text}")

    rows = patch_resp.json()
    if not rows:
        raise HTTPException(status_code=404, detail="Roadmap item not found")

    row = rows[0]
    return {
        "id": row.get("item_key"),
        "status": row.get("status"),
        "progress": row.get("progress"),
    }

@router.get("")
def get_roadmap(user_id: str = ""):
    if not user_id:
        raise HTTPException(status_code=401, detail="Missing user_id")
    safe_user = _safe_user_id(user_id)

    latest = _load_latest_roadmap_plan(safe_user)
    if latest:
        plan = latest.get("plan") or {}
        return {
            "ok": True,
            "user_id": safe_user,
            "mode": plan.get("mode") or "v2",
            "next_action": latest.get("next_action"),
            "items": latest.get("items") or [],
        }

    items = _generate_roadmap_with_llm_from_behavior(safe_user)
    saved = _save_roadmap_plan(safe_user, "v2", items)

    return {
        "ok": True,
        "user_id": safe_user,
        "mode": "v2",
        "next_action": saved.get("next_action"),
        "items": saved.get("items") or [],
    }

@router.post("/refresh")
def refresh_roadmap(payload: RoadmapRefreshRequest):
    safe_user = _safe_user_id(payload.user_id)
    items = _generate_roadmap_with_llm_from_behavior(safe_user)
    saved = _save_roadmap_plan(safe_user, "v2", items)
    return {
        "ok": True,
        "user_id": safe_user,
        "mode": "v2",
        "next_action": saved.get("next_action"),
        "items": saved.get("items") or [],
    }

@router.patch("/items/{item_id}")
def update_roadmap_item(item_id: str, payload: RoadmapItemUpdateRequest):
    safe_user = _safe_user_id(payload.user_id)
    status = (payload.status or "todo").strip().lower()
    if status not in {"todo", "doing", "done"}:
        raise HTTPException(status_code=400, detail="Invalid status")

    updated = _update_roadmap_item_db(safe_user, item_id, status, payload.progress)
    return {
        "ok": True,
        "user_id": safe_user,
        "item_id": updated.get("id"),
        "status": updated.get("status"),
        "progress": updated.get("progress"),
    }
